### ISSUE TITLE
invite me

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AlphaMcpe/AlphaMC#2]

**Comment by XtremePlayzCODE** [comment]
and give me owner access, i need to change these reepo and org names to capital stuff

**Comment by daniktheboss** [comment]
Capital stuff?

**Comment by XtremePlayzCODE** [comment]
THE ORG NAME AND REPO NAME ARE NOT CAPITALIZED AND ITS FUCKING ANNOYING ME

**Comment by daniktheboss** [comment]
What do u mean? It's all capitalized

**Comment by XtremePlayzCODE** [comment]
omfg

**Comment by XtremePlayzCODE** [comment]
ivite me to the orf

**Comment by daniktheboss** [comment]
I did

**Comment by XtremePlayzCODE** [comment]
it should be AlphaMCPE and AlphaMC not AlphaMcpe and AlphaMc

**Comment by XtremePlayzCODE** [comment]
you invited me to the repo...

**Comment by XtremePlayzCODE** [comment]
go into the org, click invite someone, search for me, and then go into people, click on Admin next to me, and change it to owner

**Comment by daniktheboss** [comment]
I changed it but idk idk its not showing

**Comment by XtremePlayzCODE** [comment]
yeah for some reason

**Comment by XtremePlayzCODE** [comment]
anyways idk

**Comment by daniktheboss** [comment]
Can u post ur readme?

**Comment by XtremePlayzCODE** [comment]
i have it let me cmmit

**Comment by daniktheboss** [comment]
Com/alphamc/core?? No

**Comment by XtremePlayzCODE** [comment]
yeah

**Comment by XtremePlayzCODE** [comment]
its fine dude

**Comment by XtremePlayzCODE** [comment]
there

**Comment by daniktheboss** [comment]
-_-

**Comment by XtremePlayzCODE** [comment]
fuck this shit

**Comment by XtremePlayzCODE** [comment]
stop deleting my shit dude

**Comment by daniktheboss** [comment]
Calm down! And do everything under core

**Comment by XtremePlayzCODE** [comment]
fucking python does not like capital folder names

**Comment by XtremePlayzCODE** [comment]
were not doing fucking c++

**Comment by daniktheboss** [comment]
Python checks if it's capital
